# Generated by Django 5.1.3 on 2024-11-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('emblem', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('emblem', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('cardId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('priority', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(max_length=100)),
                ('subtask', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('userId', models.ManyToManyField(blank=True, to='join_app.user')),
            ],
        ),
    ]
