# Generated by Django 5.1.3 on 2024-11-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0003_create_guest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='emblem',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
