# Generated by Django 5.1.3 on 2024-11-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0004_contact_color_contact_emblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emblem',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
