# Generated by Django 5.1.3 on 2024-11-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0005_user_color_user_emblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cardId',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='task',
            name='userId',
            field=models.ManyToManyField(to='join_app.user'),
        ),
    ]
