# Generated by Django 5.1.3 on 2024-11-27 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0005_remove_task_subtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_tasks', to='join_app.contact')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_contacts', to='join_app.task')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskUser',
        ),
    ]
