# Generated by Django 5.1.3 on 2024-11-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0006_taskcontact_delete_taskuser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskcontact',
            unique_together={('task', 'contact')},
        ),
        migrations.AddField(
            model_name='contact',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='taskcontact',
            name='checked',
        ),
    ]
