# Generated by Django 5.1.3 on 2024-11-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0007_alter_taskcontact_unique_together_contact_checked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='checked',
        ),
        migrations.AddField(
            model_name='taskcontact',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
